"""Create the data_sensitivity taxonomy and pii_high/pii_low policy tags via
the Data Catalog REST API, grant governance fine-grained read access on
pii_high, and write the resulting resource names to dbt/policy_tags.yml.

Uses the REST API rather than the gcloud CLI: the stable
`gcloud data-catalog taxonomies` command group has no `create` subcommand
(confirmed against current docs — only `import`, which needs an
undocumented serialized-taxonomy JSON schema). The REST API's
projects.locations.taxonomies.create / .policyTags.create endpoints are
well-documented and stable. Authenticates with the human's own gcloud ADC
access token — no service account keys. Idempotent: safe to re-run.
"""
import os
import subprocess
from pathlib import Path

import requests
from policy_tags_lib import merge_binding

REPO_ROOT = Path(__file__).parent.parent
POLICY_TAGS_PATH = REPO_ROOT / "dbt" / "policy_tags.yml"

API = "https://datacatalog.googleapis.com/v1"
FINE_GRAINED_READER_ROLE = "roles/datacatalog.categoryFineGrainedReader"


def _get_access_token() -> str:
    result = subprocess.run(
        ["gcloud", "auth", "print-access-token"],
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout.strip()


def _headers(token: str) -> dict:
    return {"Authorization": f"Bearer {token}", "Content-Type": "application/json"}


def _find_by_display_name(items: list, display_name: str):
    for item in items:
        if item.get("displayName") == display_name:
            return item
    return None


def ensure_taxonomy(token: str, parent: str) -> str:
    resp = requests.get(f"{API}/{parent}/taxonomies", headers=_headers(token))
    resp.raise_for_status()
    existing = _find_by_display_name(resp.json().get("taxonomies", []), "data_sensitivity")
    if existing:
        return existing["name"]
    resp = requests.post(
        f"{API}/{parent}/taxonomies",
        headers=_headers(token),
        json={
            "displayName": "data_sensitivity",
            "activatedPolicyTypes": ["FINE_GRAINED_ACCESS_CONTROL"],
        },
    )
    resp.raise_for_status()
    return resp.json()["name"]


def ensure_policy_tag(token: str, taxonomy_name: str, display_name: str) -> str:
    resp = requests.get(f"{API}/{taxonomy_name}/policyTags", headers=_headers(token))
    resp.raise_for_status()
    existing = _find_by_display_name(resp.json().get("policyTags", []), display_name)
    if existing:
        return existing["name"]
    resp = requests.post(
        f"{API}/{taxonomy_name}/policyTags",
        headers=_headers(token),
        json={"displayName": display_name},
    )
    resp.raise_for_status()
    return resp.json()["name"]


def grant_fine_grained_reader(token: str, policy_tag_name: str, member: str) -> None:
    resp = requests.post(f"{API}/{policy_tag_name}:getIamPolicy", headers=_headers(token))
    resp.raise_for_status()
    policy = resp.json()
    updated = merge_binding(policy, FINE_GRAINED_READER_ROLE, member)
    resp = requests.post(
        f"{API}/{policy_tag_name}:setIamPolicy",
        headers=_headers(token),
        json={"policy": updated},
    )
    resp.raise_for_status()


def main() -> None:
    project_id = os.environ["GCP_PROJECT_ID"]
    location = os.environ["BQ_LOCATION"]
    parent = f"projects/{project_id}/locations/{location}"

    token = _get_access_token()

    print(f"==> Ensuring taxonomy data_sensitivity exists in {location}")
    taxonomy_name = ensure_taxonomy(token, parent)
    print(f"    {taxonomy_name}")

    print("==> Ensuring policy tag pii_high exists")
    pii_high = ensure_policy_tag(token, taxonomy_name, "pii_high")
    print(f"    {pii_high}")

    print("==> Ensuring policy tag pii_low exists")
    pii_low = ensure_policy_tag(token, taxonomy_name, "pii_low")
    print(f"    {pii_low}")

    governance_sa = f"persona-governance@{project_id}.iam.gserviceaccount.com"
    print(f"==> Granting {FINE_GRAINED_READER_ROLE} on pii_high to {governance_sa}")
    grant_fine_grained_reader(token, pii_high, f"serviceAccount:{governance_sa}")

    POLICY_TAGS_PATH.parent.mkdir(parents=True, exist_ok=True)
    POLICY_TAGS_PATH.write_text(
        "# Generated by scripts/01_policy_tags.py — do not edit by hand, do not commit.\n"
        f'pii_high: "{pii_high}"\n'
        f'pii_low: "{pii_low}"\n'
    )
    print(f"\n==> Policy tags setup complete. Resource names written to {POLICY_TAGS_PATH}")


if __name__ == "__main__":
    main()
